sen-newface/msm-yeahcheese

- yeahcheese/database/migrations/2020_05_12_015817_create_events_tables.php
> eventsのマイグレーションファイルの作成

- yeahcheese/app/Event.php
> Eventモデルの追加

- yeahcheese/database/migrations/2020_05_12_015817_create_events_tables.php
#43 
- user_idをbigIntegerに直しました。
- 書き方を7.xのバージョンに直しました。
> eventsのmigrationファイルの修正 

- yeahcheese/resources/lang/en/auth.php
#30 
lang/ja/auth.phpを作るか迷いましたが、en/auth.phpを書きかえるだけにしました
確認お願いします
> [ログイン]エラー表示 

- yeahcheese/resources/views/layouts/template.blade.php
- #7  共用テンプレートを追加しました。
- イベント一覧、ログイン、登録のリンクを適宜直します。
- ログアウトの処理を実装する必要があります。
- ほぼモックなので見た目も後ほど修正する必要があります。
> layoutsにtemplate.blade.phpを追加

- yeahcheese/resources/views/events_list.blade.php
- resources/views/event_list.blade.phpが追加されています
- Controllerを作成したあとに内容を変更する必要があるかもしれません
> イベント一覧画面のbladeのモックを作成しました

- yeahcheese/resources/views/layouts/template.blade.php
- 存在しない値を参照していたために発生していたエラーを修正しました #60
- 手元の環境で表示まで確認しています
- この際、テスト表示のために作成・編集したファイルは取り除いてあります
> template.blade.phpのエラー修正

- yeahcheese/app/Event.php
- yeahcheese/app/Http/Controllers/EventController.php
- yeahcheese/app/Picture.php
- yeahcheese/app/User.php
- yeahcheese/database/seeds/DatabaseSeeder.php
- yeahcheese/database/seeds/EventsTableSeeder.php
- yeahcheese/database/seeds/PicturesTableSeeder.php
- yeahcheese/database/seeds/UsersTableSeeder.php
- yeahcheese/resources/views/events_list.blade.php
> [イベント一覧-機能]イベント全取得 

- yeahcheese/app/Http/Controllers/Auth/LoginController.php
- yeahcheese/app/Http/Controllers/EventController.php
- yeahcheese/resources/views/events_list.blade.php
#32 
リンク先追加とid別で一覧表示
where->with でちゃんとできているのか不安
イベントは作れますが写真を追加できていないのでテストができていません
レビューよろしくお願いします
> [イベント一覧-機能]ログインチェック

- yeahcheese/resources/views/layouts/template.blade.php
#50 #70 
コピペしただけ
動作確認済み
レビューよろしくお願いします
> homeとlogoutのリンク追加

- yeahcheese/app/Http/Controllers/EventController.php
- yeahcheese/resources/views/events_list.blade.php
> [イベント一覧-機能]掲載期間外のイベントは見れないようにする

- yeahcheese/resources/views/layouts/template.blade.php
> [fix-共用テンプレート]テンプレートの修正

- yeahcheese/resources/views/layouts/app.blade.php
- yeahcheese/resources/views/welcome.blade.php
#84 
laravelの文字をYeahCheeseに変更
ログイン、登録、認証キー入力のリンクの場所を右上から中央へ変更
確認よろしくお願いします
> [提案]indexページをつくる

- yeahcheese/routes/web.php
#94 
middlewareの適用範囲をグループ化しました
確認よろしくお願いします
> [refactor-全体]middlewareの適用範囲をグループ化する

- yeahcheese/app/Http/Controllers/Api/EventController.php
- yeahcheese/app/Http/Controllers/Api/PictureController.php
#91 #92 
- EventController
- fetchメソッド, updateメソッドを追加しました
- useを書きました
- PictureController
- fetchメソッド, storeメソッド, destroyメソッドを追加しました
- useを書きました
- 動作確認してません
> APIのコントローラーを作成してメソッドを追加

- yeahcheese/routes/api.php
#90 
- route/api.phpにAPI用のルーティング情報を記述しました
動作確認はしていません。
> API用のルーティング情報を記述

- yeahcheese/app/Http/Controllers/Auth/RegisterController.php
#101 
ユーザー登録後のリンクがhomeになっていたので、イベント一覧へ変更しました
確認よろしくお願いします。
> [イベント一覧]アカウント作成後のリンクをイベント一覧にする

- yeahcheese/tests/Feature/Api/EventControllerTest.php
#112 
PR #107 にテストがなかったので新規で作成しました。
手元で動作確認とテストが通ることを確認しています。
> fetchAPIのテストを作成

- yeahcheese/database/factories/EventFactory.php
- yeahcheese/database/factories/PictureFactory.php
[こちら](https://github.com/sen-newface/msm-yeahcheese/pull/113#discussion_r426381225)のレビューでの提案を受けてファクトリーの設定ファイルを作成しました。
現在$faker->imageで画像を持って来られなくなってしまっているので、PictureFactoryのpathの部分は暫定的に$faker->wordで生成された単語に拡張子を付与しています。
tinkerを使ってEventFactory, PictureFactoryともにモデルの作成ができることを確認しています。
> ファクトリーの設定ファイルを追加

- yeahcheese/tests/Feature/Api/EventControllerTest.php
- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#114 
・setUpを作成して適応させました
確認よろしくお願いします
> [refactor-イベント編集]PictureControllerTestにSetUpを作る

- yeahcheese/app/Http/Controllers/EventController.php
- yeahcheese/resources/views/events_list.blade.php
- yeahcheese/resources/views/layouts/template.blade.php
#87 
・今のままだとイベントに100枚写真があったら100枚表示してしまうので、（作業に余裕ができたら）数枚だけを表示するようにしたい
確認よろしくお願いします
> [イベント一覧-機能]写真のサムネイルを表示

- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#120 
手元でのテストOKです
確認よろしくお願いします
> PictureControllerTestのSuccessGetPathでfactoryを使う

- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#131 
- GetPathとGetPathListは別issueで修正中
- DeletePictureはテスト通ってます
> PictureControllerTestのDeletePictureでfactoryを使う

- yeahcheese/.env.testing
```
php artisan key:generate --env=testing
```
> .env.testing に APP_KEY 追加

- yeahcheese/app/Http/Controllers/Api/PictureController.php
- yeahcheese/app/Http/Resources/PictureResources.php
- yeahcheese/routes/api.php
- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#140 
- データにある全ての写真をもってくるのではなく、イベントに紐づく写真のみもってくるように変更
手元のテストOKです
レビューよろしくお願いします
> PictureAPIのlistをイベントIDに紐づくように変更する

- yeahcheese/app/Http/Controllers/Api/PictureController.php
- yeahcheese/app/Picture.php
- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#5 
・画像サイズが100KB以上で200MB以下なのかチェック
・拡張子がJPEGかチェック
レビューよろしくお願いします
> storeAPIに画像バリデーションを追加

- yeahcheese/resources/js/api.js
- yeahcheese/resources/js/index.js
- yeahcheese/resources/views/event_update.blade.php
- フォームに入力された値をAPIを使って保存できるようになりました。
- フォームに入力された値が正しくない場合
- エラーメッセージを表示するようになりました。
- 正しい値でなければ保存されません。
> イベント編集でupdateAPIにリクエストを送信

- yeahcheese/app/Http/Controllers/Api/PictureController.php
- yeahcheese/app/Http/Requests/StorePictureRequest.php
- yeahcheese/app/Picture.php
- yeahcheese/tests/Feature/Api/PictureControllerTest.php
#157 
pictureのフォームリクエストを作りました
storeAPIをフォームリクエストを使った形に修正しました
レビューよろしくお願いします
> formrequestを使う、テストが通らないやつをつくる

- yeahcheese/resources/js/api.js
- yeahcheese/resources/js/index.js
#11 
・イベント編集画面で画像をアップロードできるようにしました
・画像の表示を新しい順に変更しました
レビューよろしくお願いします
> 画像アップロードリクエストの作成

- yeahcheese/app/Http/Controllers/EventController.php
#181 
EventController内のif文周辺をリファクタしました。
- edit関数内のif文で早期returnを行うようにしました
- show関数内でifのネストが深くなっていたので修正しました
手元の環境で動作確認を行っています。
> EventController内のif文を含む関数内で早期returnを使うように変更

- yeahcheese/app/Http/Requests/ApiRequest.php
- yeahcheese/resources/js/api.js
- yeahcheese/resources/js/app.js
- yeahcheese/resources/js/bootstrap.js
- yeahcheese/resources/js/components/EventEditorComponent.vue
- yeahcheese/resources/js/components/PictureComponent.vue
#89 
- 無駄なスペースを削除
- phpcsでエラーが出ていた箇所を訂正
訂正後→index.phpでWARNINGが出ているだけ
確認よろしくお願いします。
> phpcsでエラーが出ていた部分を修正

- yeahcheese/resources/views/layouts/template.blade.php
> ヘッダーのログインと新規登録が英語になっていたので日本語に修正

- yeahcheese/public/css/style.css
- yeahcheese/resources/js/components/EventEditorComponent.vue
- yeahcheese/resources/js/components/PictureComponent.vue
- yeahcheese/resources/views/layouts/template.blade.php
#201 
- ファイル選択フォームの見た目を修正、テンプレートに直接数行js書き込み
- ついでにタイトルとかのフォームを修正
> イベント編集画面のファイル選択フォームの見た目修正

- yeahcheese/tests/Feature/EventControllerTest.php
#164 
- duskは使えないので、assertSeeとかで表示されてるか確認するためのテストとメソッドを用意
- 現状 '/' と 'events/search' しかみてないので中身をそれぞれのissueで書く
- テストは通ってます
> 表示テストのEventControllerTestを用意

- yeahcheese/tests/Feature/EventControllerTest.php
#210 
- 認証済みユーザのイベント一覧を表示
手元でテスト通ってます。
> イベント一覧画面のテスト

- yeahcheese/resources/views/events_list.blade.php
画像一覧のチェックボックスが画面を小さくすると乱れてしまったので訂正しました
確認よろしくお願いします
> チェックボックスのデザインをレスポンシブ対応に変更

- yeahcheese/tests/Feature/EventControllerTest.php
#16 
- controllerでviewを呼び出してるだけなので、画面表示確認のみ
手元でテストは通ってます。
> 認証キー入力画面テスト

- yeahcheese/app/Event.php
- yeahcheese/app/Http/Controllers/EventController.php
#149 
モデルにメソッドを作成して、controllerをすっきりさせました
確認よろしくお願いします
> イベントの作成者かどうかを判定するメソッドを追加する
