laravel/composer.lock

botのプルリク消してしまったので改めて
Bumps [symfony/http-foundation](https://github.com/symfony/http-foundation) from 5.0.5 to 5.0.8.
- [Release notes](https://github.com/symfony/http-foundation/releases)
- [Changelog](https://github.com/symfony/http-foundation/blob/master/CHANGELOG.md)
- [Commits](https://github.com/symfony/http-foundation/compare/v5.0.5...v5.0.8)
Signed-off-by: dependabot[bot] <support@github.com>

Bump symfony/http-foundation from 5.0.5 to 5.0.8 in /laravel

---

yeahcheese/app/Event.php
yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/resources/views/event_create.blade.php

- #58 イベント保存時のバリデーション機能を追加しました
- バリデーションの内容はEventモデルに、バリデーションの処理はEventControllerに記述しています
- [#64で頂いた修正案](https://github.com/sen-newface/msm-yeahcheese/pull/64#pullrequestreview-410672802) #65 EventControllerのstore関数のリファクタを行いました
バリデーションを通った場合はイベントが保存されてindexにリダイレクトすることを、通らなかった場合は保存せずに作成ページに留まることを確認しています。
レビューよろしくお願いします。

イベントのバリデーション

---

yeahcheese/routes/web.php

#75 
- ルーティングを編集して閲覧に制限をかけました
- ログインしていないユーザが制限されているページにアクセスするとログイン画面にリダイレクトされます
手元の環境で動作確認済みです。

middlewareを使って非ログインユーザが閲覧できるページを制限

---

yeahcheese/app/Event.php
yeahcheese/resources/views/event_create.blade.php

#80 についてのPRです。
- 日付関連のバリデーションがわかりにくく、また内容がかぶっている部分があったので修正しました
- 公開開始日のバリデーション内容を「明日以降」から「今日以降」に変更しました
- 公開終了日のバリデーション内容から「明日以降」を削除しました
- 上記に伴ってエラーメッセージも修正しています
- フォームにおいて、個別のエラーメッセージのほかに、フォームの値のどれかが正しくないというメッセージを作成ボタン上部に表示するようにしました
手元の環境で動作確認を行っています。

[fix]バリデーションの内容とエラーメッセージの修正

---

yeahcheese/app/Event.php
yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/resources/views/events_list.blade.php

#96 
- 検索や絞り込みをスコープで行えるようにしました
- これに伴ってblade.phpで期間外の表示をしないようにする処理を削除しました
- 追加したイベントスコープは下記の通りです
- ユーザーIDでの絞り込み
- 公開開始日が指定日より前/後であるか
- 公開終了日が指定日より前/後であるか
- 修正中にイベント一覧画面で日付での絞り込みは不要ではないかという結論になり、現状の画面では絞り込みはしていません（機能だけある状態です）
手元で公開開始日のスコープは動作確認しています。

[fix]イベント一覧画面でスコープを使って検索するように変更

---

yeahcheese/resources/views/layouts/template.blade.php
yeahcheese/resources/views/welcome.blade.php

#98 
ヘッダーに認証キーのリンクを追加しました。
認証キー入力　という名前から　イベント検索　という名前に変更しました。
確認よろしくお願いします。

[fix-共有テンプレート]ヘッダーに認証キー入力へのリンク

---

yeahcheese/app/Http/Controllers/Api/PictureController.php
yeahcheese/routes/api.php
yeahcheese/tests/Feature/Api/PictureControllerTest.php

#15 
- ルートをapi/pictures/destroyからapi/pictures/destroy/{id}に変更。picturesのidを指定する。

APIのdestroyメソッドとテストの作成

---

yeahcheese/app/Event.php
yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/resources/views/event.blade.php
yeahcheese/resources/views/search.blade.php
yeahcheese/routes/web.php

- イベント表示ページのURLはこれまで/events/show/と表示されていましたが、/events/show?auth_key=12345678のように表示するように変更しました。 #95 
- /events/search/経由だけでなく、/events/show?auth_key="認証キー"形式でも各イベントの詳細ページへアクセスできるようになります
- この変更に伴って、showへのアクセスはPOSTリクエストではなくGETリクエストを利用するように変更しました
- 公開開始日以降公開終了日以前のイベントのみが表示されるように変更しました
- show関数のリファクタを行いました
手元の環境で意図した通りに動作することを確認しています。

イベント表示ページに複数の改修

---

yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/resources/views/search.blade.php

[こちら](https://github.com/sen-newface/msm-yeahcheese/pull/116#discussion_r426408583)で頂いた改修案を反映しました
- イベント検索で対象のイベントが見つからなかった際のリダイレクトにエラーメッセージをつけました
- 合わせてテンプレートも編集し、エラーメッセージを表示するようにしています
- 赤くしたりした方が目につきやすそうなので、#59に対応する際にまとめて対応したいと思います
手元の環境で動作確認を行っています。

イベントが見つからず検索画面にリダイレクトする際にエラーメッセージを表示する

---

yeahcheese/tests/Feature/Api/PictureControllerTest.php

テスト内容をファクトリーを使う形に変更しました
getPathListのテストは動きますが、このブランチでは他のテストがエラーを出してしまうため、動作確認の際には他のテスト関数をコメントアウトする必要があります
この点については他の方のPR（#133 #135）で修正されています
レビューよろしくお願いいたします

getPathList APIのテストをファクトリーを使う形に変更

---

yeahcheese/resources/views/events_list.blade.php

#128 #127 
イベント一覧画面のテンプレートを編集し、表示されるサムネイル画像の数を最大3枚に制限しました
手元の環境でイベントに紐づいている画像が0〜4枚の時の表示をそれぞれ確認しています
レビューよろしくお願いいたします

イベント一覧画面で表示されるサムネイルの数を最大3枚に制限

---

yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/resources/views/event.blade.php

#85 
- EventCopntrollerのshowでイベントに紐付いた写真を取得する際になにもなかったときにviewにエラーメッセージを渡す

イベント表示の際画像が1枚もない場合に、ないことを表示

---

yeahcheese/app/Http/Controllers/EventController.php

#143 
- eventを取ってくる際に期間内で絞り込むのをやめた
- eventを取ってきたあとで、release_dateとend_dateとtodayを比較して、公開期間外の場合のエラーメッセージを表示する

公開期間外の場合のエラーメッセージを追加

---

yeahcheese/.eslintrc.json

yeahcheese/.eslint.jsonを編集し、ESLintの設定を変更しました。
- 拡張子が.tsファイルの時のみTypeScript用のチェックを行うようにしました
手元の環境において*.js, *.ts, *vueそれぞれのファイルで動作確認を行っています。

ESLint使用時、TypeScript用のチェックを行わないように変更

---

yeahcheese/app/Providers/RouteServiceProvider.php

#183 
RouteServiceProviser.phpでHOME='/home'になっていたのを修正

ログイン状態で'/register'に飛ぶと'/'にリダイレクト

---

yeahcheese/app/Event.php
yeahcheese/app/Http/Controllers/EventController.php
yeahcheese/app/Http/Requests/StoreEventRequest.php
yeahcheese/app/Http/Requests/StorePictureRequest.php
yeahcheese/resources/views/event_create.blade.php

#176 #180 
- Eventのstoreメソッドをフォームリクエストを使うように変更しました
- Eventモデルのバリデーションは使っている場所がないので削除しました
- 「入力した値が正しくありません」は必要ないので削除しました
レビューよろしくお願いします。

storeメソッドのバリデーションのFormRequest化、必要のないエラー文の削除

---

yeahcheese/app/Http/Requests/StoreEventRequest.php

#194 
イベント編集の際は、公開開始日が今日以前でもOKだったので
それに合わせてイベント作成の際も公開開始日が今日以前でもOKにしました。
StoreEventRequestとUpdateEventRequestを１つにまとめようと思いましたが、Updateにはrequiredがないためやめました。
レビューよろしくお願いします

公開開始日を今日より前にできるように変更

---

yeahcheese/resources/views/event_create.blade.php
yeahcheese/resources/views/event_show.blade.php
yeahcheese/resources/views/search.blade.php

#205 
- イベント作成時に公開開始日が今日からじゃなくても作成できるようになるので変更
- イベント閲覧時に画像が登録されてない場合、画像をクリックすると拡大表示しますのテキストが表示されないように変更
- 認証キー入力画面で句読点がなかったところを追加
- 認証キーの文字がlabelだとあまりに小さいのでh4に変更

jumbotron内テキストを変更

---

yeahcheese/app/Http/Requests/UpdateEventRequest.php
yeahcheese/resources/js/components/EventEditorComponent.vue
yeahcheese/tests/Feature/Api/EventControllerTest.php

#174 
今日から今日が掲載期間のイベントを作れるように変更しました。
別issue(#194 )でイベント作成のときも公開開始日が今日以前にできるように変更します。
レビューよろしくお願いします

日付の更新でエラーが出ない

---

yeahcheese/tests/Feature/EventControllerTest.php

イベント表示画面(events/show)に接続した時の表示とリダイレクトのテストを作成しました。
下記内容をテストしています
- 正しいauth_keyが与えられた時、event内容が表示されている
- 無効なauth_keyが与えられた時、events/searchにリダイレクトする
- auth_keyなしで接続された時、events/searchにリダイレクトする
手元の環境で動作を確認しています。

イベント表示画面の表示テスト

---

yeahcheese/tests/Feature/EventControllerTest.php

EventControllerTest.php内に規約違反になっている部分があったため修正しました。
変更内容は下記の通りです
- 空行が存在していたので削除
手元の環境でphpcsを走らせ、該当部分の警告が消えていることを確認しています。

EventControllerTest.phpの規約違反部分を修正

---

yeahcheese/resources/js/components/EventEditorComponent.vue

イベント更新画面において開発者ツールなどを使い不正な値のリクエストを何度も送信した場合、同一内容のエラーメッセージが増えるバグを修正しました。
参考画像:
- updateEventでLaravel側からレスポンスを受け取るたびにエラーメッセージを格納している変数を空にするように変更しました
- 今回の修正とはあまり関係ありませんが、コンソールにエラーを表示する際にconsole.errorではなくconsole.logを使用していたのを修正しました
手元の環境で動作確認をしています。

不正な値のまま何度も更新ボタンを押すと同一内容のエラーメッセージが増えるバグを修正

---

yeahcheese/resources/js/components/EventEditorComponent.vue

公開開始日と公開終了日のバリデーションの状態が同期されていなかったため、バリデーションエラーが発生した際に片方の日付を修正して正しい公開範囲に変更しても、もう片方の日付バリデーションの状態が変更されず、更新リクエストを送信できない不具合が発生していたのを修正しました。
手元の環境で動作を確認していますが、急ぎの修正だったため確認漏れがあるかもしれません。

イベント編集画面で日付を正しい公開範囲に変更しても更新できない不具合が発生していたのを修正
